### ISSUE TITLE
Promote a user

### ISSUE THREAD

**Issue by bucherfa** [LAM-GeMont/fehlzeiten#89] opened 2021-11-26 19:00 UTC
change the role from Teacher to Coordinator
(permisson is only checked once)

**Comment by axelkrusechavela** [comment] 2021-12-01 22:25
The coordinator role in our app is going to be associated with an IServ role.
But that may be a point: to check on every login, if the coordinator role is there and not just when creating the account.

**Comment by axelkrusechavela** [comment] 2021-12-02 15:20
Duplicate of #129

**Closed as completed by axelkrusechavela** 2021-12-02 15:20 UTC
