### ISSUE TITLE
As a coordinator, i want to record if a student has been excused for an absence during an exam in order to archive this information.

### ISSUE THREAD

**Issue by jonaslanglotz** [LAM-GeMont/fehlzeiten#8] opened 2021-09-09 13:02 UTC
8 SP

**Comment by bucherfa** [comment] 2021-11-19 19:05
mark a absence lesson as an exam

**Comment by bucherfa** [comment] 2021-11-26 18:49
duplicate of #86

**Closed as completed by bucherfa** 2021-11-26 18:49 UTC
Labels: story
